sudo: required

services:
    - docker

cache:
    directories:
        - /home/travis/docker/
env:
    global:
        - DOCKER_CACHE_FILE=/home/travis/docker/cache.tar.gz
        - DOCKER_IMAGE_NAME=dockerlaravel54skelton_laravel

before_install:
#    - if [ -f ${DOCKER_CACHE_FILE} ]; then gunzip -c ${DOCKER_CACHE_FILE} | docker load; fi
    - ls -l ${DOCKER_CACHE_FILE}
    - docker version
    - docker-compose -f docker-compose.yml up -d

script:
    - docker-compose version
    - docker-compose -f docker-compose.yml run laravel php artisan dusk
    - docker history -q ${DOCKER_IMAGE_NAME}
    - if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then mkdir -p $(dirname ${DOCKER_CACHE_FILE}) ; docker save $(docker history -q ${DOCKER_IMAGE_NAME} | grep -v '<missing>') | gzip > ${DOCKER_CACHE_FILE}; fi
notifications:
    slack:
        secure: es+wev0q7eQzBT/fIlAHFKxVZhH/SKEaSEkuu8GdQmt6WaXeB/vbKa3cvEO5WVJ+h5Y/Az0hPmLratVPKR9KAVhjvqWJYaAb+XWqrUcnpIhh6eyVObFSSFSnOBTlh0QQ9b6lXBm+kQH3GJtDIil/LpukYWwP2fZjtTi71GwOIzAiocjF01p52yvSukp8JZUmtCsdJ3K3ERCtdmkxwfYPbNr3VGAEXe9lOWBbuR8suu83/A26qMTXy1DcHaF0Bghu0uzpPoou6ZoRtOMekqnkajK6cpQfq7r9vFY/h1Kg7LjeuaznjldsKMjVwaHgUeippEFO0mrW2idiNO/oCiv35pQIH5mryIHBWLUCKttRRACZEjO9SZVZpqh7MkhC1a2diwRI47XNMI3htCfFibCLi7SqZFMzYk8OjJ5EGCxIwWuRa3K1zBCOT/tNsWIXjEfJ5tV4BJeVw/oMbVfWs1Vrti4e0+l/SVEkTkCwHqvhMx/UFPQKp5p2JgRFOGwfH+d4SePM4eIbh/kfYkdtdbuwIbV8vApUjXFG3MtHj9MpbVbw6nrgs/1nXYzi0W74eTXQwc3pNFm8z0kMh0IKZqoZiAABWp647M83BqG3D6j7PQ7EwQRfn6hRjHyn3eCRoNMB8f0jdqH3abHWgbZ4+s1yY0ctil2Qa7VIOmbCp5f+xtk=
